# permissions for end users to edit namespaceclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: namespace-class
    app.kubernetes.io/managed-by: kustomize
  name: namespaceclass-editor-role
rules:
- apiGroups:
  - namespaceclass.josephb.org
  resources:
  - namespaceclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - namespaceclass.josephb.org
  resources:
  - namespaceclasses/status
  verbs:
  - get
