---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - namespaceclass.josephb.org
  resources:
  - namespaceclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - namespaceclass.josephb.org
  resources:
  - namespaceclasses/finalizers
  verbs:
  - update
- apiGroups:
  - namespaceclass.josephb.org
  resources:
  - namespaceclasses/status
  verbs:
  - get
  - patch
  - update
